<Project>
    
    <PropertyGroup>
        <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsPackable)' != 'false'">
        <Authors>NovoDwarf</Authors>
        <Copyright>NovoDwarf</Copyright>
        <PackageProjectUrl>https://github.com/NovoDwarf/Grekov</PackageProjectUrl>
        <RepositoryUrl>https://github.com/NovoDwarf/Grekov</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    
</Project>
