<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>$(GrekovProviderFSVersion)</Version>
        <AssemblyVersion>$(GrekovProviderFSAssemblyVersion)</AssemblyVersion>
        <FileVersion>$(GrekovProviderFSAssemblyVersion)</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Grekov\Grekov.csproj" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="11.0.0-rc.1.26425.128" />
      <PackageReference Include="NovoDwarf.FS" Version="1.0.1" />
    </ItemGroup>
    
</Project>
