<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>$(GrekovReaderXmlVersion)</Version>
        <AssemblyVersion>$(GrekovReaderXmlAssemblyVersion)</AssemblyVersion>
        <FileVersion>$(GrekovReadersXmlAssemblyVersion)</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Grekov\Grekov.csproj" />
        <PackageReference Include="NovoDwarf.FS" Version="1.0.1" />
    </ItemGroup>
    
</Project>
