<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.2.0-dev1</Version>
        <AssemblyVersion>1.2.0.1</AssemblyVersion>
        <FileVersion>1.2.0.1</FileVersion>
    </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Grekov\Grekov.csproj" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0" />
	</ItemGroup>
    
</Project>
