<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>$(GrekovProviderBinaryVersion)</Version>
        <AssemblyVersion>$(GrekovProviderBinaryAssemblyVersion)</AssemblyVersion>
        <FileVersion>$(GrekovProviderBinaryAssemblyVersion)</FileVersion>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Grekov.Binary\Grekov.Binary.csproj" />
      <ProjectReference Include="..\Grekov\Grekov.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NovoDwarf.FS" Version="1.0.1" />
    </ItemGroup>

</Project>
