<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Grekov" Version="1.1.0-dev1" />
      <PackageReference Include="Tomlyn" Version="2.10.1" />
    </ItemGroup>

</Project>
