<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>$(GrekovStorageInMemoryVersion)</Version>
        <AssemblyVersion>$(GrekovStorageInMemoryAssemblyVersion)</AssemblyVersion>
        <FileVersion>$(GrekovStorageInMemoryAssemblyVersion)</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Grekov\Grekov.csproj" />
    </ItemGroup>

</Project>
